build(nix): add required SystemConfiguration build input on darwin
This fixes the following error produced by `nix shell .`:

```
>   = note: ld: warning: directory not found for option '-L/private/tmp/nix-build-git-disjoint-0.10.163.drv-0/source/target/release/build/libz-sys-768d411a6207564b/out/lib64'
>           ld: framework not found SystemConfiguration
>           clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
>
> error: could not compile `git-disjoint` (bin "git-disjoint") due to 1 previous error
```