chore!: remove support for i686-unknown-linux-musl
Since CI started failing with this message

```
      Compiling const-sha1 v0.2.0
  error[E0599]: no variant or associated item named `Stdin` found for enum `owo_colors::Stream` in the current scope
     --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/cross-0.2.4/src/shell.rs:426:57
      |
  426 |     const OWO: owo_colors::Stream = owo_colors::Stream::Stdin;
      |                                                         ^^^^^ variant or associated item not found in `owo_colors::Stream`

  For more information about this error, try `rustc --explain E0599`.
  error: could not compile `cross` due to previous error
  error: failed to compile `cross v0.2.4`, intermediate artifacts can be found at `/tmp/cargo-installylgXSS`
```

and this target was only provided on a best-effort basis.